//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackRockAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalPath
    {
        public long Id { get; set; }
        public string BaseUrl { get; set; }
        public string Identifier { get; set; }
        public string DefaultImageUrl { get; set; }
    }
}
