//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackRockAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public long SchemeTypeId { get; set; }
        public long SchemeCategoryId { get; set; }
        public long SchemePlanId { get; set; }
        public long RiskId { get; set; }
        public long BenchmarkId { get; set; }
        public long HorizoneId { get; set; }
        public long GoalId { get; set; }
        public decimal MinLumpsumAmount { get; set; }
        public decimal MinSipAmount { get; set; }
        public decimal ExpenseRatio { get; set; }
        public decimal AUM { get; set; }
        public System.DateTime InceptionDate { get; set; }
        public decimal EntryLoad { get; set; }
        public decimal ExitLoad { get; set; }
        public long FundManagerId { get; set; }
        public string Description { get; set; }
        public bool IsOpenEndedFund { get; set; }
        public decimal QuandlCode { get; set; }
        public bool isGrowth { get; set; }
        public bool isDividend { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime ManagingSince { get; set; }
    
        public virtual Benchmark Benchmark { get; set; }
        public virtual InvestmentGoal InvestmentGoal { get; set; }
        public virtual InvestmentHorizone InvestmentHorizone { get; set; }
        public virtual Risk Risk { get; set; }
        public virtual SchemeCategory SchemeCategory { get; set; }
        public virtual SchemePlan SchemePlan { get; set; }
        public virtual SchemeType SchemeType { get; set; }
        public virtual User User { get; set; }
    }
}
