//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlackRockAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long SchemeId { get; set; }
        public decimal Amount { get; set; }
        public decimal Units { get; set; }
        public long TransactionType { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public long InvestmentType { get; set; }
    }
}
